# build-live-negative-control.ps1 — Phase 6C-H6
# Reusable builder for live-executed target-gate negative controls
param(
    [Parameter(Mandatory=$true)][string]$ParentRunDir,
    [Parameter(Mandatory=$true)][string]$NegativeName,
    [Parameter(Mandatory=$true)][string]$TargetFile,
    [Parameter(Mandatory=$true)][string]$SearchPattern,
    [Parameter(Mandatory=$true)][string]$ReplacePattern,
    [Parameter(Mandatory=$true)][string]$TargetScenario,
    [Parameter(Mandatory=$true)][string]$ExpectedClassification = "FAIL_TARGET_GATE",
    [string]$Group = "B",
    [string]$OutputDir = ""
)
$ErrorActionPreference = "Continue"
$H = "C:\Codex_App_Factory\harness"
$ts = (Get-Date).ToString("o")

if (-not $OutputDir) { $OutputDir = "$H\runs\$NegativeName" }
if (Test-Path $OutputDir) { Remove-Item -Recurse -Force $OutputDir -ErrorAction SilentlyContinue }
Copy-Item -Recurse $ParentRunDir -Destination $OutputDir -Force

$targetPath = Join-Path $OutputDir $TargetFile
if (-not (Test-Path $targetPath)) { Write-Output (@{ok=$false;error="Target file not found: $TargetFile"} | ConvertTo-Json); exit 1 }

$beforeHash = (Get-FileHash $targetPath -Algorithm SHA256).Hash
$content = Get-Content $targetPath -Raw
$content = $content -replace [regex]::Escape($SearchPattern), $ReplacePattern
$content | Out-File -Encoding utf8 -LiteralPath $targetPath
$afterHash = (Get-FileHash $targetPath -Algorithm SHA256).Hash

$faultManifest = @{
    negativeId = $NegativeName; parentRunId = (Split-Path $ParentRunDir -Leaf)
    targetLayer = if ($Group -eq "B") { "TenantIsolationAcceptance" } else { "UsageQuotaMeteringAcceptance" }
    targetScenario = $TargetScenario; expectedClassification = $ExpectedClassification
    injectedFaultDescription = "Search: $SearchPattern -> Replace: $ReplacePattern"
    changedFiles = @(@{path=$TargetFile; beforeSha256=$beforeHash; afterSha256=$afterHash; operation="modify"})
    injectionMethod = "text-replace"; createdAt = $ts; createdBy = "build-live-negative-control.ps1"
    noNewSpawnAgent = $true; notes = "Auto-generated by H6 negative-control builder"
}
$manifestPath = Join-Path $OutputDir "fault-manifest.json"
$faultManifest | ConvertTo-Json -Depth 4 | Out-File -Encoding utf8 -LiteralPath $manifestPath

# Write run script
$runDir = $OutputDir -replace '\\','/'
@"
var p=require("path"),f=require("fs");
process.chdir("$runDir");
var s=require("./worker-1-workspace/src/store.js"),sd=require("./worker-1-workspace/src/seedData.js");
var r=require("./worker-5-workspace/src/scenarioRunner.js"),w=require("./worker-5-workspace/src/acceptanceWriter.js");
s.resetStore();sd.seedSampleData(s);
var rs=r.runAllScenarios();
var rd=p.join(process.cwd(),"reports");
if(!f.existsSync(rd))f.mkdirSync(rd,{recursive:true});
w.writeAcceptanceJson(rs,p.join(rd,"tenant-metering-acceptance-report.json"));
var t=rs.results.map(function(x){return{id:x.id,passed:x.passed,error:x.error||null}});
var r2=t.filter(function(x){return!x.passed});
f.writeFileSync(p.join(rd,"acceptance-transcript.json"),JSON.stringify({negativeId:"$NegativeName",targetScenario:"$TargetScenario",totalScenarios:rs.totalScenarios,passed:rs.passed,failed:rs.failed,verdict:rs.verdict,transcript:t},null,2),"utf8");
console.log(JSON.stringify({ok:true,verdict:rs.verdict,passed:rs.passed,failed:rs.failed,failedScenarios:r2.map(function(x){return x.id}),faultInjected:$($beforeHash -ne $afterHash ? "true" : "false")}));
"@ | Out-File -Encoding ascii -LiteralPath (Join-Path $OutputDir "_run.js")

Write-Output (@{ok=$true; outputDir=$OutputDir; faultManifest=$manifestPath; beforeHash=$beforeHash; afterHash=$afterHash; hashChanged=($beforeHash -ne $afterHash)} | ConvertTo-Json)
exit 0
