# generate-final-report.ps1 — Phase 6C-O-R1
# Generates final report from machine evidence (final-verdict-report.json).
param(
    [Parameter(Mandatory=$true)][string]$RunDir,
    [Parameter(Mandatory=$true)][string]$PhaseName,
    [Parameter(Mandatory=$false)][string]$Description = ""
)

$ErrorActionPreference = "Continue"
$verdictPath = Join-Path $RunDir "final-verdict-report.json"

if (-not (Test-Path $verdictPath)) {
    $verdict = "FAIL"
    $verdictNote = "final-verdict-report.json NOT FOUND"
    $hardGates = $null; $failures = @()
} else {
    try {
        $vr = Get-Content $verdictPath -Raw -Encoding UTF8 | ConvertFrom-Json
        $verdict = $vr.verdict
        $hardGates = $vr.hardGates
        $failures = $vr.hardGateFailures
        $phaseMode = if ($vr.phaseMode) { $vr.phaseMode } else { "Project" }
        $verdictNote = "Final verdict derived from machine evidence via finalize-run-verdict.ps1 (mode: $phaseMode)."
    } catch {
        $verdict = "FAIL"; $verdictNote = "final-verdict-report.json PARSE ERROR"
        $hardGates = $null; $failures = @()
    }
}

# Build gate table — FIXED: iterate PSObject.Properties
$gateLines = ""
if ($hardGates) {
    foreach ($prop in $hardGates.PSObject.Properties) {
        $k = $prop.Name
        # Skip metadata fields
        if ($k -match 'Note$' -or $k -eq "phaseMode" -or $k -eq "notApplicablePolicy" -or $k -eq "fixtureTests") { continue }
        $v = $prop.Value
        $gateLines += "| $k | $v |`n"
    }
    # Add fixtureTests if present
    if ($hardGates.PSObject.Properties.Name -contains "fixtureTests") {
        $gateLines += "| fixtureTests | $($hardGates.fixtureTests) |`n"
    }
}

$failSection = ""
if ($failures -and $failures.Count -gt 0) {
    $failSection = "## 4. Gate Failures`n`n"
    foreach ($f in $failures) { $failSection += "- $f`n" }
} else {
    $failSection = "## 4. Gate Failures`n`nNone. All hard gates PASS.`n"
}

$report = @"
# ${PhaseName} Final Report

**Date**: $(Get-Date -Format "yyyy-MM-dd")
**Phase**: $PhaseName
**Status**: **$verdict**

> $verdictNote

---

## 1. Overall Status

**${PhaseName}**: **$verdict**

$Description

---

## 2. Final Verdict Derivation

Final verdict is mechanically derived from `final-verdict-report.json`, generated by `finalize-run-verdict.ps1`. Never derived from exitCode alone, final report prose, or agent self-report.

---

## 3. Hard Gate Summary

| Hard Gate | Status |
|---|---|
$gateLines

$failSection

---

## 5. Capabilities NOT Provided

- Real backend: NOT IMPLEMENTED
- Real database: NOT IMPLEMENTED
- Real login authentication: NOT IMPLEMENTED
- Production security: NOT PROVIDED
- Real cloud deployment: NOT IMPLEMENTED
- 6+ Builder concurrency: NOT TESTED
- Overnight orchestration: NOT TESTED
- Strong cognitive isolation: NOT PROVEN
- OS-level isolation: NOT PROVIDED

---

## 6. Audit Bundle

See sidecar `*.zip.meta.json` for authoritative ZIP digest.
"@

$reportPath = Join-Path $RunDir "${PhaseName}_FINAL_REPORT.md"
$utf8 = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($reportPath, $report, $utf8)
Write-Output "Report generated: $reportPath"
exit 0