# Codex Factory V3.1 — CI Provider Adapter
# Supports: local-ci-simulated, github-actions-template, external-ci-placeholder
param(
    [Parameter(Mandatory=$true)] [string]$Action,
    [string]$JobName = "",
    [string]$Command = "",
    [string]$WorkDir = ".",
    [string]$Provider = "local-ci-simulated",
    [string]$CiRunId = $null,
    [switch]$Json
)

$RepoRoot = (Get-Location).Path
if (-not $CiRunId) { $CiRunId = "CI-" + (Get-Date -Format "yyyyMMdd-HHmmss") + "-" + (Get-Random -Minimum 1000 -Maximum 9999) }

function Invoke-LocalCISimulated {
    param([string]$JobName, [string]$Command, [string]$WorkDir)
    $started = Get-Date
    $ciArtifactsDir = "$RepoRoot/artifacts/ci-runs/$CiRunId"
    New-Item -ItemType Directory -Path $ciArtifactsDir -Force | Out-Null
    $stdoutPath = "$ciArtifactsDir/stdout.log"
    $stderrPath = "$ciArtifactsDir/stderr.log"

    $snapshotOk = Test-Path "$RepoRoot/outputs/V2_9/V2_9_IMMUTABLE_SNAPSHOT_MANIFEST.json"

    try {
        Push-Location "$RepoRoot/$WorkDir"
        $output = Invoke-Expression $Command 2>&1
        $exitCode = $LASTEXITCODE
        Pop-Location

        $stdoutOut = $output | Where-Object { $_ -isnot [System.Management.Automation.ErrorRecord] }
        $stderrOut = $output | Where-Object { $_ -is [System.Management.Automation.ErrorRecord] }
        $stdoutOut | Out-File -Encoding utf8 $stdoutPath
        $stderrOut | Out-File -Encoding utf8 $stderrPath

        $status = if ($exitCode -eq 0) { "PASS" } elseif ($exitCode -eq 999) { "BLOCKED" } else { "FAIL" }
    } catch {
        $exitCode = 1; $status = "FAIL"
        $_ | Out-File -Encoding utf8 $stderrPath
    }

    @{
        ci_run_id = $CiRunId; provider = $Provider; job_name = $JobName
        command = $Command; command_redacted = $Command -replace '(sk-[A-Za-z0-9]+|api_key=[A-Za-z0-9]+|token=[A-Za-z0-9]+)','***REDACTED***'
        exit_code = $exitCode; stdout_path = $stdoutPath; stderr_path = $stderrPath
        artifact_paths = @($stdoutPath, $stderrPath)
        commit_or_snapshot_ref = "CODEX-FACTORY-V2-20260717"
        started_at = $started.ToString("o"); finished_at = (Get-Date).ToString("o")
        status = $status; snapshot_verified = $snapshotOk; secret_policy_result = "NOT_CHECKED"
        non_claims = @("local-ci-simulated is NOT a real CI provider", "No cloud runner involved")
    }
}

function New-GitHubActionsTemplate {
    param([string]$JobName, [string]$Command, [string]$WorkDir)
    @"
# GitHub Actions template generated by Codex Factory V3.1
# TARGET: Copy to .github/workflows/ and customize
name: $JobName
on: [push, pull_request]
jobs:
  factory-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: cd $WorkDir && $Command
      - uses: actions/upload-artifact@v4
        with: { name: factory-artifacts, path: artifacts/ }
"@
}

switch ($Action) {
    "run" {
        if ($Provider -eq "local-ci-simulated") {
            $receipt = Invoke-LocalCISimulated -JobName $JobName -Command $Command -WorkDir $WorkDir
        } elseif ($Provider -eq "github-actions-template") {
            $template = New-GitHubActionsTemplate -JobName $JobName -Command $Command -WorkDir $WorkDir
            $templatePath = "$RepoRoot/outputs/V3_1/gha-template-$CiRunId.yml"
            $template | Out-File -Encoding utf8 $templatePath
            $receipt = @{
                ci_run_id = $CiRunId; provider = $Provider; job_name = $JobName
                status = "SKIPPED"; command = $Command
                artifact_paths = @($templatePath)
                non_claims = @("github-actions-template is a template, NOT an executed run")
            }
        } elseif ($Provider -eq "external-ci-placeholder") {
            $receipt = @{
                ci_run_id = $CiRunId; provider = $Provider; job_name = $JobName
                status = "SKIPPED"; command = $Command
                non_claims = @("external-ci-placeholder is NOT_IMPLEMENTED", "No external CI connected")
            }
        }
        $receipt | ConvertTo-Json -Depth 4 | Out-File -Encoding utf8 "$RepoRoot/artifacts/ci-runs/$CiRunId/ci-receipt.json"
        if ($Json) { $receipt | ConvertTo-Json -Depth 4 }
    }
    "list" {
        Get-ChildItem "$RepoRoot/artifacts/ci-runs" -Directory -ErrorAction SilentlyContinue | ForEach-Object { Write-Output $_.Name }
    }
    default { Write-Output "Usage: -Action [run|list] ..." }
}