# Real Agent Bridge Packet Generator
# Part of: FACTORY-R2.3-I-SKILL-RUNTIME-SCALING-AND-REAL-AGENT-BRIDGE
# Generates consumable packets for real Codex agent sessions

param([string]$FactoryRoot = "C:\Codex_App_Factory")

$script:FR = $FactoryRoot

function New-AgentRunPacket {
    param(
        [string]$ProjectId,[string]$PhaseId,[string]$AgentId,[string]$ProjectType,
        [string[]]$SkillIds,[string]$TaskDescription
    )
    . (Join-Path $script:FR "runtime\skill-content-loader.ps1")

    $packet = [PSCustomObject]@{
        packetId = "ARP-$ProjectId-$PhaseId-$AgentId-$(Get-Date -Format 'yyyyMMddHHmmss')"
        packetType = "agent-run-packet"
        generatedAt = Get-Date -Format "yyyy-MM-ddTHH:mm:sszzz"
        projectId = $ProjectId
        phaseId = $PhaseId
        agentId = $AgentId
        projectType = $ProjectType
        taskDescription = $TaskDescription
        loadedSkillRefs = @()
        allowedCapabilities = @()
        forbiddenActions = @()
        requiredOutputs = @()
        handoffRequired = $true
        trustStatusNote = "Generated by Factory R2.3-I bridge. Verify skill trust levels before agent execution."
        sourceRefs = @()
    }

    foreach ($sid in $SkillIds) {
        $lr = Load-SkillContent -SkillId $sid -AgentId $AgentId -ProjectId $ProjectId -PhaseId $PhaseId -ProjectType $ProjectType -IsLocalFirst $true
        if ($lr.Loaded) {
            $packet.loadedSkillRefs += [PSCustomObject]@{
                skillId = $sid
                name = $lr.SkillSummary.name
                version = $lr.SkillSummary.version
                trustLevel = $lr.SkillSummary.trustLevel
                status = $lr.SkillSummary.status
                summary = if ($lr.SkillSummary.instructionsSummary.Length -gt 500) { $lr.SkillSummary.instructionsSummary.Substring(0, 500) + "..." } else { $lr.SkillSummary.instructionsSummary }
                allowedTools = $lr.SkillSummary.allowedTools
                forbiddenActions = $lr.SkillSummary.forbiddenActions
                triggerConditions = $lr.SkillSummary.triggerConditions
            }
            $packet.allowedCapabilities += $lr.SkillSummary.allowedTools
            $packet.forbiddenActions += $lr.SkillSummary.forbiddenActions
            $packet.sourceRefs += $lr.SkillSummary.inputRefs
        } else {
            Write-Warning "Skill $sid not loaded: $($lr.Reason)"
        }
    }

    # Deduplicate
    $packet.allowedCapabilities = $packet.allowedCapabilities | Select-Object -Unique
    $packet.forbiddenActions = $packet.forbiddenActions | Select-Object -Unique

    return $packet
}

function New-SkillContextPacket {
    param([string]$SkillId,[string]$AgentId,[string]$ProjectId)
    . (Join-Path $script:FR "runtime\skill-content-loader.ps1")
    $lr = Load-SkillContent -SkillId $SkillId -AgentId $AgentId -ProjectId $ProjectId -PhaseId "CONTEXT-ONLY" -ProjectType "fullstack-admin" -IsLocalFirst $true
    if (-not $lr.Loaded) { return $null }
    return [PSCustomObject]@{
        packetId = "SCP-$SkillId-$AgentId-$(Get-Date -Format 'yyyyMMddHHmmss')"
        packetType = "skill-context-packet"
        skillId = $SkillId
        targetAgent = $AgentId
        summary = $lr.SkillSummary
        usageCaveats = @("Trust level: $($lr.SkillSummary.trustLevel)", "Status: $($lr.SkillSummary.status)", "auditPassed != runtimeVerified for non-CAP-SKILL-004 skills")
    }
}

function New-VerificationCommandPacket {
    param([string]$ProjectId,[string]$PhaseId,[string]$AgentId,[string[]]$SkillIds)
    $p = [PSCustomObject]@{packetId="VCP-$ProjectId-$PhaseId-$(Get-Date -Format 'yyyyMMddHHmmss')";packetType="verification-command-packet";projectId=$ProjectId;phaseId=$PhaseId;requiredChecks=@()}
    foreach ($sid in $SkillIds) { $p.requiredChecks += "Verify $sid is in loadedSkillRefs"; $p.requiredChecks += "Verify $sid forbiddenActions are not violated" }
    $p.requiredChecks += "Verify handoff contains all required fields"
    $p.requiredChecks += "Verify skill usage ledger has entries for all loaded skills"
    return $p
}

Write-Verbose "Real Agent Bridge Packet Generator loaded."
