'use strict';

function generateReport(scenarios) {
  const total = scenarios.length;
  const passed = scenarios.filter(s => s.passed).length;
  const failed = scenarios.filter(s => !s.passed).length;
  const elapsed = scenarios.reduce((s, x) => s + (x.elapsedMs || 0), 0);

  const lines = [];
  lines.push('# H5 Mini Inventory Ops — Acceptance Scenario Report');
  lines.push('');
  lines.push('**Worker**: worker-4');
  lines.push('**Generated**: ' + new Date().toISOString());
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push('| Total  | ' + total + ' |');
  lines.push('| Passed | ' + passed + ' |');
  lines.push('| Failed | ' + failed + ' |');
  lines.push('| Rate   | ' + (total ? (passed / total * 100).toFixed(1) + '%' : 'N/A') + ' |');
  lines.push('| Total elapsed | ' + elapsed + 'ms |');
  lines.push('');
  lines.push('## Scenario Results');
  lines.push('');
  lines.push('| # | Scenario | Result | Details | Time |');
  lines.push('|---|----------|--------|---------|------|');
  scenarios.forEach((s, i) => {
    const status = s.passed ? '✅ PASS' : '❌ FAIL';
    lines.push('| ' + (i + 1) + ' | ' + s.name + ' | ' + status + ' | ' + (s.details || '-') + ' | ' + (s.elapsedMs || 0) + 'ms |');
  });

  if (failed > 0) {
    lines.push('');
    lines.push('## Failures');
    scenarios.filter(s => !s.passed).forEach(s => {
      lines.push('');
      lines.push('### ' + s.name);
      lines.push('');
      lines.push('- **Error**: ' + s.details);
      lines.push('- **Elapsed**: ' + (s.elapsedMs || 0) + 'ms');
    });
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Report generated by worker-4 acceptance runner.*');

  return lines.join('\n');
}

module.exports = { generateReport };
